server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/supermall?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jpa:
    open-in-view: false
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: "*"